require("plugins.lsp_config")
require("plugins.theme")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.tmux_navigator")
require("plugins.prettier")
require("plugins.barbar")
-- require("plugins.breadcrumbs")
require("plugins.commenting")
require("plugins.telescope")
-- require("plugins.copilot")
-- require("plugins.rustaceanvim")
require("plugins.rust-tools")
require("plugins.dap")
